update

diff --git a/zram b/zram
--- a/zram
+++ b/zram
@@ -263,10 +263,14 @@ start() {
       return 1
     fi
   else
-    [ -n "$zram_comp_algo" ] \
-      && { echo "$zram_comp_algo" > "/sys/block/${_zram}/comp_algorithm" 2> /dev/null \
-      || ewarn "Invalid compression algorithm chosen, using default. This kernel may not support this algorithm."; }
-    echo "$_mem_to_alloc" > "/sys/block/${_zram}/disksize" 2> /dev/null
+    if [ -z "$zram_comp_algo" ] || ! echo "$zram_comp_algo" > "/sys/block/${_zram}/comp_algorithm" 2> /dev/null; then \
+      ewarn "Invalid compression algorithm chosen, using default. This kernel may not support this algorithm."
+    fi
+    if ! echo "$_mem_to_alloc" > "/sys/block/${_zram}/disksize" 2> /dev/null; then
+      eerror "Failed to write /dev/${_zram} size"
+      _rmlock
+      return 1
+    fi
   fi
 
   [ -n "$zram_algo_params" ] \
