update

diff --git a/zram b/zram
--- a/zram
+++ b/zram
@@ -38,11 +38,12 @@ dev_name="${RC_SVCNAME#*.}"
 : "${zram_algo_params:=""}"
 : "${zram_backing_dev:=""}"
 
+LC_COLLATE=C
+
 depend() {
   need localmount swap
   _after=""
   _runlevel="$(rc-status -r)"
-  LC_COLLATE=C
   for svc in "${RC_PREFIX%/}"/etc/runlevels/"${_runlevel}"/zram*; do
     if [ "${svc##*/}" = "$RC_SVCNAME" ]; then
       break
@@ -67,28 +68,21 @@ _timeout() {
 _getswap() {
   _dev="$1"
   _return=""
-  # _ifs="$IFS"
-  # IFS="$(printf "\u0a")"
-  while read -r swap_dev; do
-    if [ "$_dev" = "${swap_dev% *}" ]; then
-      _return="$swap_dev"
+  while read -r _swap_dev; do
+    if [ "$_dev" = "${_swap_dev% *}" ]; then
+      _return="$_swap_dev"
     fi
+    break
   done << EOF 
   $(swapon --show=label,name --raw --noheadings)
 EOF
-  # for swap_dev in $(swapon --show=label,name --raw --noheadings); do
-  #   if [ "$_dev" = "${swap_dev% *}" ]; then
-  #     _return="$swap_dev"
-  #   fi
-  # done
-  # IFS=$_ifs
   echo "$_return"
 }
 
 _checkswap() {
   _dev="$1"
-  for swap_dev in $(swapon --show=label --raw --noheadings); do
-    [ "$_dev" = "$swap_dev" ] && return 0
+  for _swap_dev in $(swapon --show=label --raw --noheadings); do
+    [ "$_dev" = "$_swap_dev" ] && return 0
   done
   return 1
 }
@@ -125,17 +119,35 @@ start() {
 
   while read -r _mem_header _mem_size _; do [ "$_mem_header" != "MemTotal:" ] || break; done < /proc/meminfo
   _mem_total="$((_mem_size / 1024))"
-
-  if _timeout 5 read -r _refcnt < /sys/module/zram/refcnt; then
-    _zram="zram${_refcnt}"
-    if ! [ -b "/dev/${_zram}" ]; then
-      if _timeout 5 read -r _hot < /sys/class/zram-control/hot_add; then
+  
+  for _zram_dev in /sys/block/zram*; do
+    read -r _state < "${_zram_dev}/initstate"
+    if [ "$_state" -eq 0 ]; then
+      _zram="${_zram_dev##*/}"
+      break
+    fi
+  done
+  if [ -z "$_zram" ]; then
+    if _timeout 5 read -r _hot < /sys/class/zram-control/hot_add; then
         _zram="zram${_hot}"
-      else
-        eend 1 "Failed to hot add a zram device"
-      fi
+    else
+      eend 1 "Failed to hot add a zram device"
     fi
   fi
+  # if _timeout 5 read -r _refcnt < /sys/module/zram/refcnt; then
+  #   if [ "$_refcnt" -eq 0 ]; then
+  #     _zram="zram0"  
+  #   else
+  #     _zram="zram${_refcnt}"
+  #   fi
+  #   if ! [ -b "/dev/${_zram}" ]; then
+  #     if _timeout 5 read -r _hot < /sys/class/zram-control/hot_add; then
+  #       _zram="zram${_hot}"
+  #     else
+  #       eend 1 "Failed to hot add a zram device"
+  #     fi
+  #   fi
+  # fi
   
   einfo "Initializing zram device: /dev/${_zram}"
   
@@ -212,7 +224,7 @@ stop() {
   if [ -n "$_swap" ]; then
     _dev="${_swap#* }"
     swapoff -L "$dev_name" > /dev/null 2>&1 \
-    && _timeout 5 echo 1 > "/sys/block/${_dev##*/}/reset" \
+    && _timeout 5 echo 1 > "${_dev}/reset" \
     && _timeout 5 echo "${_dev##*zram}" > /sys/class/zram-control/hot_remove \
     && einfo "Removed zram device: ${dev_name}"
   fi
