update

diff --git a/zram b/zram
--- a/zram
+++ b/zram
@@ -245,11 +245,11 @@ start() {
 
   if [ -n "$zram_backing_dev" ]; then
     if echo "$zram_backing_dev" > "/sys/block/${_zram}/backing_dev" 2> /dev/null; then
-      if [ -z "$zram_comp_algo" ] || ! echo "$zram_comp_algo" > "/sys/block/${_zram}/comp_algorithm" 2> /dev/null; then
+      if ! [ -n "$zram_comp_algo" ] || ! echo "$zram_comp_algo" > "/sys/block/${_zram}/comp_algorithm" 2> /dev/null; then
         ewarn "Invalid compression algorithm chosen, using default. This kernel may not support this algorithm."
       fi
       echo "$_mem_to_alloc" > "/sys/block/${_zram}/disksize" 2> /dev/null
-      if [ -z "$zram_writeback" ] || echo "$zram_writeback" > "/sys/block/${_zram}/writeback" 2> /dev/null; then
+      if [ -n "$zram_writeback" ] && echo "$zram_writeback" > "/sys/block/${_zram}/writeback" 2> /dev/null; then
           if [ -z "$zram_writeback_limit" ] || ! echo "$((${zram_writeback_limit%%[A-Za-z]*}<<20>>12))" > "/sys/block/${_zram}/writeback_limit" 2> /dev/null \
             || ! echo 1 > "/sys/block/${_zram}/writeback_limit_enable" 2> /dev/null; then
             ewarn "Failed to write /dev/${_zram} writeback limit"
@@ -263,9 +263,9 @@ start() {
       return 1
     fi
   else
-    [ -n "$zram_comp_algo" ] \
-      && { echo "$zram_comp_algo" > "/sys/block/${_zram}/comp_algorithm" 2> /dev/null \
-      || ewarn "Invalid compression algorithm chosen, using default. This kernel may not support this algorithm."; }
+      if ! [ -n "$zram_comp_algo" ] || ! echo "$zram_comp_algo" > "/sys/block/${_zram}/comp_algorithm" 2> /dev/null; then
+        ewarn "Invalid compression algorithm chosen, using default. This kernel may not support this algorithm."
+      fi
     if ! echo "$_mem_to_alloc" > "/sys/block/${_zram}/disksize" 2> /dev/null; then
       eerror "Failed to write /dev/${_zram} size"
       _rmlock
