Added writeback configuration and reorganized the code.

diff --git a/zram-gen b/zram-gen
--- a/zram-gen
+++ b/zram-gen
@@ -1,6 +1,6 @@
 #!/sbin/openrc-run
 
-description=""
+description="Manages zram swap devices"
 
 start_pre() {
   ebegin "Starting zram-gen"
@@ -18,127 +18,108 @@ start_pre() {
 }
 
 start() {
-  local enable="" size="" comp_algo="" algo_params="" \
+  local size="" comp_algo="" algo_params="" \
     mem_limit="" priority="" discard_opt="" backing_dev="" \
-    swapon_discard_opt="" mem_to_alloc="" status="" i=0
+    swapon_discard_opt="" mem_to_alloc="" swap_devs="" i=0
 
-  supported_algo=$(sed "s/[][]//g" /sys/block/zram0/comp_algorithm)
   read -r supported_algo < /sys/block/zram0/comp_algorithm
 
   while read -r mem_header mem_size _; do [ "$mem_header" != "MemTotal:" ] || break; done < /proc/meminfo
-  mem_size=$((mem_size / 1024))
+  mem_total=$((mem_size / 1024))
 
-  einfo "Total host memory: ${mem_size}MiB"
+  while read -r dev _; do [ "$dev" != "Filename" ] && swap_devs="$swap_devs $dev"; done < /proc/swaps
 
-  eval "enable=\$ZRAM${i}"
-  while [ "$enable" == "true" ]; do
+  einfo "Total host memory: ${mem_total}MiB"
+
+  while eval "[ '\${ZRAM${i}:-false}' == 'true' ]"; do
     eval "size=\${ZRAM${i}_SIZE:-25%}"
     eval "discard_opt=\${ZRAM${i}_DISCARD_OPT:-both}"
     eval "priority=\${ZRAM${i}_PRIORITY:-32767}"
     eval "mem_limit=\$ZRAM${i}_MEM_LIMIT"
     eval "comp_algo=\$ZRAM${i}_COMP_ALGO"
-    eval "algo_dict=\$ZRAM${i}_ALGO_DICT"
+    eval "algo_params=\$ZRAM${i}_ALGO_PARAMS"
     eval "backing_dev=\$ZRAM${i}_BACKING_DEV"
+    eval "writeback=\${ZRAM${i}_WRITEBACK:-idle}"
+
+    for dev in $swap_devs; do
+      [ "$dev" = "/dev/zram${i}" ] \
+        && einfo "/dev/zram${i} is already mounted as a swap device" \
+        && ln --symbolic --force "/dev/zram${i}" "/var/run/zram-gen/zram${i}" \
+        && i=$((i + 1)) \
+        && continue 2
+    done
 
     [ -b "/dev/zram${i}" ] \
       || read -r _ < /sys/class/zram-control/hot_add \
-      || { eerror "Failed to hot add the zram device: /dev/zram${i}" \
+      || { eerror "Failed to hot add a zram device" \
       && break ; }
 
     einfo "Initializing zram device: /dev/zram${i}"
     
-    echo 1 > "/sys/block/zram${i}/reset"
+    echo 1 > "/sys/block/zram${i}/reset" \
+      || ewarn "Failed to reset zram device, device or resource busy" \
+      && i=$((i + 1)) \
+      && continue
 
-    ! [ -n "$backing_dev" -a -b "$backing_dev" ] \
-      || echo "$backing_dev" > "/sys/block/zram${i}/backing_dev" \
-      || ewarn "Failed to write zram${i} backing device"
-    
-    if [ -n "$comp_algo" ]; then
-      { echo "$comp_algo" > "/sys/block/zram${i}/comp_algorithm" 2> /dev/null \
-        && status="${status} Algorithm: ${comp_algo}" ; }  \
-        || ewarn "Invalid compression algorithm chosen, using default. This kernel only support: [ ${supported_algo} ]"
-
-      if [ "${comp_algo%%:*}" != "${comp_algo##*:}" ]; then
-        
-        algo_params="algo=${comp_algo%%:*}"
-        case ${comp_algo##*:} in
-          [0-9]*|-[0-9]*)
-            algo_params="${algo_params} level=${comp_algo##*:}"
-            status="${status} Algorithm Lvl: ${comp_algo}"
-            ;;
-          *)
-            ewarn "Invalid compression algorithm level"
-            ;;
-        esac
-        ! [ -n "$algo_dict" -a -f "$algo_dict" ] \
-          || algo_params="${algo_params} dict=${algo_dict}"
-        echo "${algo_params}" > "/sys/block/zram${i}/algorithm_params"
-      fi
-    fi
+    [ -n "$backing_dev" ] \
+      && { echo "$backing_dev" > "/sys/block/zram${i}/backing_dev" \
+      || ewarn "Failed to write zram${i} backing device" ; }
 
     case "${size##*[0-9]}" in
       %)
-        mem_to_alloc="$((${size%\%} * mem_size / 100))"
-        ;;
-      x|X)
-        val="$(printf "%.2f" "${size%[xX]}" | { IFS=. read -r x y; printf "%d" $(( (x * 100) + y  )) ; })"
-        mem_to_alloc="$(( val * mem_size / 100 ))"
+        mem_to_alloc="$((${size%\%} * mem_total / 100))"
         ;;
       [KkMmGgTtPpEeZzYy]|[KkMmGgTtPpEeZzYy][Ii][Bb])
         mem_to_alloc=$size
         ;;
       *)
         ewarn "Invalid value for size, using default"
-        mem_to_alloc="$((25 * mem_size / 100))"
+        mem_to_alloc="$((25 * mem_total / 100))"
         ;;
     esac
 
     echo "${mem_to_alloc}MiB" > "/sys/block/zram${i}/disksize"
 
-    status="Size: ${mem_to_alloc}"
+    [ -n "$backing_dev" -a -n "$writeback" ] \
+      && { echo "$writeback" > "/sys/block/zram${i}/writeback" \
+      || ewarn "Failed to set zram${i} writeback" ; }
 
-    if [ -n "$mem_limit" ]; then
-      case "${mem_limit##*[0-9]}" in
-        [KkMmGgTtPpEeZzYy]|[KkMmGgTtPpEeZzYy][Ii][Bb])
-          echo "$mem_limit" > "/sys/block/zram${i}/mem_limit"
-          status="Memory Limit: ${mem_limit}"
-          ;;
-        *)
-          ewarn "Invalid value for memory limit, using default"
-          ;;
-      esac
-    fi
+    [ -n "$mem_limit" ] \
+      && { echo "$mem_limit" > "/sys/block/zram${i}/mem_limit" \
+      || ewarn "Invalid value for memory limit, using default" ; }
+
+    [ -n "$comp_algo" ] \
+      && { echo "$comp_algo" > "/sys/block/zram${i}/comp_algorithm" 2> /dev/null \
+      || ewarn "Invalid compression algorithm chosen, using default. This kernel only support: [ ${supported_algo} ]" ; }
+    
+    [ -n "$algo_params" ] \
+      && { echo "algo=${comp_algo%%:*} ${algo_params}" > "/sys/block/zram${i}/algorithm_params" \
+      || ewarn "Invalid compression algorithm parameters" ; }
 
     case "$discard_opt" in
-      false|none)
-        ;;
-      true|both)
+      both)
         swapon_discard_opt="--discard"
         ;;
-      once)
-        swapon_discard_opt="--discard=once"
-        ;;
-      pages)
-        swapon_discard_opt="--discard=pages"
+      once|pages)
+        swapon_discard_opt="--discard=${discard_opt}"
         ;;
       *)
         ewarn "Invalid value for discard, using default"
         swapon_discard_opt="--discard"
         ;;
     esac
-
-    ! [ -n "$priority" -a "$priority" -gt 32767 ] \
-      || { ewarn "Invalid swap priority, using default." \
-      && priority=32767 ; }
+    
+    [ "$priority" -gt 32767 ] \
+      && ewarn "Invalid swap priority, using default." \
+      && priority=32767
     
     { mkswap --uuid clear --label "ZRAM${i}" "/dev/zram${i}" &> /dev/null \
       && swapon "$swapon_discard_opt" --priority "$priority" "/dev/zram${i}" &> /dev/null \
-      && ln --symbolic --force "/dev/zram${i}" "/var/run/zram-gen/zram${i}" ; } \
-      || { eerror "Failed to c" \
-      && break ; }
+      && ln --symbolic --force "/dev/zram${i}" "/var/run/zram-gen/zram${i}" \
+      && einfo "Successfully created zram swap device: /dev/zram${i}" ; } \
+      || eerror "Failed to initialize zram swap device: /dev/zram${i}"
 
     i=$((i + 1))
-    eval enable=\$ZRAM${i}
     sleep 0.1
   done
   eend "$?" "Failed to create zram swap device(s)"
@@ -149,9 +130,9 @@ stop() {
     ! [ -b "$device" ] && continue
     dev_name="${device##*\/}"
     einfo "Removing zram device: /dev/${dev_name}"
-    swapoff "/dev/${dev_name}"
-    rm -f "/var/run/zram-gen/${dev_name}"
-    einfo "Removed zram device: /dev/${dev_name}"
+    swapoff "/dev/${dev_name}" \
+      && rm -f "/var/run/zram-gen/${dev_name}" \
+      && einfo "Removed zram device: /dev/${dev_name}"
   done
  eend $? "Failed to remove zram device(s)"
 }
@@ -162,7 +143,7 @@ stop_post() {
     read -r refcnt < /sys/module/zram/refcnt
     if [ "$RC_CMD" != "restart" -a "$refcnt" -eq 0 ]; then
       modprobe -r zram && einfo "Zram module unloaded"
-      [ -d "/var/run/zram-gen" ] && rm -rf /var/run/zram-gen
+      [ $? -eq 0 -a -d "/var/run/zram-gen" ] && rm -rf /var/run/zram-gen
     fi
   fi
   eend $? "Failed to remove zram module"
