update

diff --git a/zram b/zram
--- a/zram
+++ b/zram
@@ -32,25 +32,23 @@ description="Manages zram devices"
 zram_label="${RC_SVCNAME#*.}"
 
 : "${zram_type:=swap}"
+: "${zram_size:=50%}"
+: "${zram_writeback_limit:=}"
+: "${zram_writeback_batch_size:=}"
+: "${zram_compressed_writeback:=}"
+: "${zram_mem_limit:=}"
+: "${zram_backing_dev:=}"
+: "${zram_comp_algo:=}"
+: "${zram_algo_params:=}"
 
-: "${zram_storage_mountpoint:=""}"
-: "${zram_storage_mode:=755}"
-: "${zram_storage_options:=noatime}"
-: "${zram_storage_owgr:=""}"
-: "${zram_storage_discard:=""}"
+: "${zram_swap_discard:=}"
+: "${zram_swap_priority:=}"
 
-: "${zram_swap_priority:=32767}"
-: "${zram_swap_discard:=both}"
-
-: "${zram_size:=25%}"
-: "${zram_writeback:=incompressible}"
-: "${zram_writeback_limit:=""}"
-: "${zram_writeback_batch_size:=""}"
-: "${zram_mem_limit:=""}"
-: "${zram_backing_dev:=""}"
-: "${zram_comp_algo:=""}"
-: "${zram_algo_params:=""}"
-: "${zram_idle:=""}"
+: "${zram_storage_mountpoint:=}"
+: "${zram_storage_mode:=}"
+: "${zram_storage_options:=}"
+: "${zram_storage_discard:=}"
+: "${zram_storage_owgr:=}"
 
 depend() {
   need localmount
@@ -63,6 +61,13 @@ depend() {
       ;;
   esac
   after modules zram.*
+}
+
+_isnum() {
+  case $1 in
+    *[!0-9]*|"") return 1;;
+  esac
+  return 0
 }
 
 _timeout() {
@@ -90,27 +95,18 @@ _rmlock() {
 _mkswap() {
   _zram="$1"
   _sop=""
-  if [ "$zram_swap_priority" -gt 32767 ] || [ "$zram_swap_priority" -lt -1 ]; then
+  if ! _isnum "$zram_swap_priority" || [ "$zram_swap_priority" -gt 32767 ] || [ "$zram_swap_priority" -lt -1 ]; then
     ewarn "Invalid swap priority, using default."
-      _sop="pri=32767"
-    else
-      _sop="pri=${zram_swap_priority}"
+    unset zram_swap_priority
   fi
+  _sop="pri=${zram_swap_priority:=32767}"
   case "$zram_swap_discard" in
-    both)
-      _sop="${_sop},discard"
-      ;;
-    once|pages)
-      _sop="${_sop},discard=${zram_swap_discard}"
-      ;;
-    none)
-      ;;
-    *)
-      ewarn "Invalid value for swap discard"
-      ;;
+    once|pages) _sop="${_sop},discard=${zram_swap_discard}";;
+    none|[Nn]|[Nn][Oo]);;
+    both|*) _sop="${_sop},discard";;
   esac
-  if mkswap --uuid random --label "$zram_label" -- "${_zram}" > /dev/null 2>&1; then
-    if swapon -o "$_sop" -- "${_zram}" > /dev/null 2>&1; then
+  if mkswap --uuid random --label "$zram_label" -- "/dev/${_zram}" > /dev/null 2>&1; then
+    if swapon --options "$_sop" -- "$_zram" > /dev/null 2>&1; then
       einfo "Successfully created zram swap: ${zram_label}"
     else
       eerror "Failed to enable zram swap: ${zram_label}"
@@ -123,12 +119,12 @@ _mkswap() {
 _rmswap() {
   _zram="$1"
   for _swap in $(swapon --show=name --raw --noheadings); do
-    if [ "$_zram" = "$_swap" ]; then
-      swapoff "$_zram" > /dev/null 2>&1
+    if [ "/dev/${_zram}" = "$_swap" ]; then
+      swapoff -- "/dev/${_zram}" > /dev/null 2>&1
       break
     fi
   done
-    _timeout 5 echo 1 > "/sys/block/${_zram##*/}/reset" \
+  _timeout 5 echo 1 > "/sys/block/${_zram}/reset" \
     && _timeout 5 echo "${_zram##*zram}" > /sys/class/zram-control/hot_remove \
     && einfo "Removed zram swap: ${zram_label}"
 }
@@ -137,20 +133,23 @@ _mkstorage() {
   _zram="$1"
   _fsop="huge_file,sparse_super,extent,^uninit_bg,dir_nlink,extra_isize,^has_journal"
   _mop="defaults"
-  if [ -n "${zram_storage_options}" ]; then
-    _mop="${_mop},${zram_storage_options}"
+  _mop="${_mop},${zram_storage_options:=noatime}"
+  case "$zram_storage_discard" in
+    [Yy]|[Yy][Ee][Ss]) _mop="${_mop},discard";;
+    [Nn]|[Nn][Oo]|*) _mop="${_mop},nodiscard";;
+  esac
+  if ! awk -v uwgr="$zram_storage_owgr" 'BEGIN {if (uwgr ~ /(^[a-z_][a-z0-9_-]*)$|(^[a-z_][a-z0-9_-]*:[a-z_][a-z0-9_-]*)$/) {exit 0} else {exit 1}}'; then
+    ewarn "Ivalid value owner:group, using default"
+    unset zram_storage_owgr
   fi
-  if [ -n "$zram_storage_discard" ] && [ "$zram_storage_discard" = "y" ]; then
-    _mop="${_mop},discard"
+  if ! awk -v mode="$zram_storage_mode" 'BEGIN {if (mode ~ /^[0-1]?[0-7]{3}$/) {exit 0} else {exit 1}}'; then
+    ewarn "Ivalid value for mode, using default"
+    unset zram_storage_mode
   fi
-  if mkfs.ext4 -m0 -O"${_fsop}" -U random -L "$zram_label" -- "${_zram}" > /dev/null 2>&1 && tune2fs -c0 -i0 -m0 -- "${_zram}" > /dev/null 2>&1; then
-    if [ -n "${zram_storage_mountpoint}" ] && mount --mkdir -t ext4 -o "$_mop" -- "${_zram}" "${zram_storage_mountpoint}" > /dev/null 2>&1; then
-      [ -n "$zram_storage_mode" ] \
-        && { chmod "${zram_storage_mode}" -- "${zram_storage_mountpoint}" > /dev/null 2>&1 \
-        || ewarn "Invalid value for mode"; }
-      [ -n "$zram_storage_owgr" ] \
-        && { chown "${zram_storage_owgr}" -- "${zram_storage_mountpoint}" > /dev/null 2>&1 \
-        || ewarn "Invalid value for owner:group"; }
+  if mkfs.ext4 -m0 -O"${_fsop}" -U random -L "$zram_label" -- "/dev/${_zram}" > /dev/null 2>&1 && tune2fs -c0 -i0 -m0 -- "/dev/${_zram}" > /dev/null 2>&1; then
+    if [ -n "$zram_storage_mountpoint" ] \
+      && checkpath --quiet --directory --mode "${zram_storage_mode:=0775}" --owner "${zram_storage_owgr:=root:root}" "$zram_storage_mountpoint" \
+      && mount -types ext4 --options "$_mop" -- "/dev/${_zram}" "$zram_storage_mountpoint" > /dev/null 2>&1; then
       einfo "Successfully created zram storage: ${zram_label}"
     else
       eerror "Failed to mount zram storage: ${zram_label}"   
@@ -163,12 +162,12 @@ _mkstorage() {
 _rmstorage() {
   _zram="$1"
   while read -r _dev _; do
-    if [ "$_zram" = "$_dev" ]; then
-      umount "$_zram" > /dev/null 2>&1
+    if [ "/dev/${_zram}" = "$_dev" ]; then
+      umount -- "/dev/${_zram}" > /dev/null 2>&1
       break
     fi
   done < /proc/mounts
-  _timeout 5 echo 1 > "/sys/block/${_zram##*/}/reset" \
+  _timeout 5 echo 1 > "/sys/block/${_zram}/reset" \
     && _timeout 5 echo "${_zram##*zram}" > /sys/class/zram-control/hot_remove \
     && einfo "Removed zram storage: ${zram_label}"
 }
@@ -194,7 +193,8 @@ start_pre() {
 
 start() {
   _zram=""
-  _mem_to_alloc=""
+  _mem_size=""
+  _mem_limit=""
   _hot=0
   _refcnt=0
   _mem_total=0
@@ -226,78 +226,95 @@ start() {
 
   case "${zram_size##*[0-9]}" in
     %)
-      _mem_to_alloc="$((${zram_size%\%} * _mem_total / 100))MiB"
+      _mem_size="$((${zram_size%\%} * _mem_total / 100))MiB"
       ;;
     [KkMmGgTtPpEeZzYy]|[KkMmGgTtPpEeZzYy][Ii][Bb])
-      _mem_to_alloc="$zram_size"
+      _mem_size="$zram_size"
       ;;
     *)
       ewarn "Invalid value for size, using default"
-      _mem_to_alloc="$((25 * _mem_total / 100))MiB"
+      _mem_size="$((50 * _mem_total / 100))MiB"
       ;;
   esac
 
+  if [ -n "$zram_mem_limit" ]; then
+    case "${zram_mem_limit##*[0-9]}" in
+      %)
+        _mem_limit="$((${zram_mem_limit%\%} * _mem_total / 100))MiB"
+        ;;
+      [KkMmGgTtPpEeZzYy]|[KkMmGgTtPpEeZzYy][Ii][Bb])
+        _mem_limit="$zram_mem_limit"
+        ;;
+      *)
+        ewarn "Invalid value for memory limit"
+        ;;
+    esac
+  fi
+
   einfo "Initializing zram device: /dev/${_zram}"
   
-  _timeout 5 echo 1 > "/sys/block/${_zram}/reset" \
-    || { eerror "Failed to reset zram device /dev/${_zram}: device or resource busy" \
-    && _rmlock \
-    && return 1; }
+  if ! _timeout 5 echo 1 > "/sys/block/${_zram}/reset"; then
+    eerror "Failed to reset zram device /dev/${_zram}: device or resource busy"
+    _rmlock
+    return 1
+  fi
 
   if [ -n "$zram_backing_dev" ]; then
     if echo "$zram_backing_dev" > "/sys/block/${_zram}/backing_dev" 2> /dev/null; then
-      if [ -n "$zram_comp_algo" ] && ! echo "$zram_comp_algo" > "/sys/block/${_zram}/comp_algorithm" 2> /dev/null; then
+      if [ -n "$zram_comp_algo" ] && echo "$zram_comp_algo" > "/sys/block/${_zram}/comp_algorithm" 2> /dev/null; then
+        [ -n "$zram_algo_params" ] \
+          && { echo "algo=${zram_comp_algo} ${zram_algo_params}" > "/sys/block/${_zram}/algorithm_params" 2> /dev/null \
+          || ewarn "Invalid compression algorithm parameters"; }
+      else
         ewarn "Invalid compression algorithm chosen, using default. This kernel may not support this algorithm."
       fi
-      echo "$_mem_to_alloc" > "/sys/block/${_zram}/disksize" 2> /dev/null
-      if [ -n "$zram_writeback" ] && echo "$zram_writeback" > "/sys/block/${_zram}/writeback" 2> /dev/null; then
-          if [ -n "$zram_writeback_limit" ] && ! echo "$((${zram_writeback_limit%%[A-Za-z]*}<<20>>12))" > "/sys/block/${_zram}/writeback_limit" 2> /dev/null \
-            || ! echo 1 > "/sys/block/${_zram}/writeback_limit_enable" 2> /dev/null; then
-            ewarn "Failed to write /dev/${_zram} writeback limit"
-          fi
-          if [ -n "${zram_writeback_batch_size}" ] && ! echo "$zram_writeback_batch_size" > "/sys/block/${_zram}/writeback_batch_size"; then
-            ewarn "Failed to write /dev/${_zram} writeback batch size"
-          fi
-      else 
-        ewarn "Failed to set /dev/${_zram} writeback"
+      echo "$_mem_size" > "/sys/block/${_zram}/disksize" 2> /dev/null
+      if [ -n "$zram_writeback_limit" ] && ! echo "$((${zram_writeback_limit%%[A-Za-z]*}<<20>>12))" > "/sys/block/${_zram}/writeback_limit" 2> /dev/null \
+        || ! echo 1 > "/sys/block/${_zram}/writeback_limit_enable" 2> /dev/null; then
+        ewarn "Failed to write /dev/${_zram} writeback limit"
       fi
+      if [ -n "${zram_writeback_batch_size}" ] && ! echo "$zram_writeback_batch_size" > "/sys/block/${_zram}/writeback_batch_size" 2> /dev/null; then
+        ewarn "Failed to write /dev/${_zram} writeback batch size"
+      fi
+        case $zram_compressed_writeback in
+          [Yy]|[Yy][Ee][Ss]) echo "yes" > "/sys/block/${_zram}/compressed_writeback" 2> /dev/null || ewarn "Failed to enable /dev/${_zram} compressed writeback";;
+          [Nn]|[Nn][Oo]|*) echo "no" > "/sys/block/${_zram}/compressed_writeback" 2> /dev/null || ewarn "Failed to enable /dev/${_zram} compressed writeback";;
+        esac
     else
       eerror "Failed to write /dev/${_zram} backing device"
       _rmlock
       return 1
     fi
   else
-    if [ -n "$zram_comp_algo" ] && ! echo "$zram_comp_algo" > "/sys/block/${_zram}/comp_algorithm" 2> /dev/null; then
+    if [ -n "$zram_comp_algo" ] && echo "$zram_comp_algo" > "/sys/block/${_zram}/comp_algorithm" 2> /dev/null; then
+      [ -n "$zram_algo_params" ] \
+        && { echo "algo=${zram_comp_algo} ${zram_algo_params}" > "/sys/block/${_zram}/algorithm_params" 2> /dev/null \
+        || ewarn "Invalid compression algorithm parameters"; }
+    else
       ewarn "Invalid compression algorithm chosen, using default. This kernel may not support this algorithm."
     fi
-    if ! echo "$_mem_to_alloc" > "/sys/block/${_zram}/disksize" 2> /dev/null; then
+    if ! echo "$_mem_size" > "/sys/block/${_zram}/disksize" 2> /dev/null; then
       eerror "Failed to write /dev/${_zram} size"
       _rmlock
       return 1
     fi
   fi
-
-  [ -n "$zram_algo_params" ] \
-    && { echo "algo=${zram_comp_algo} ${zram_algo_params}" > "/sys/block/${_zram}/algorithm_params" 2> /dev/null \
-    || ewarn "Invalid compression algorithm parameters"; }
   
-  [ -n "$zram_mem_limit" ] \
-    && { echo "$zram_mem_limit" > "/sys/block/${_zram}/mem_limit" 2> /dev/null \
-    || ewarn "Invalid value for memory limit, using default"; }
-
-  [ -n "$zram_idle" ] \
-    && { echo "$zram_idle" > "/sys/block/${_zram}/idle" 2> /dev/null \
-    || ewarn "Invalid value for idle, using default"; }
-
-  service_set_value zram "${_zram}:${zram_type}"
-
+  if [ -n "$_mem_limit" ] && ! echo "$zram_mem_limit" > "/sys/block/${_zram}/mem_limit" 2> /dev/null; then
+    eerror "Failed to write /dev/${_zram} memory limit"
+    _rmlock
+    return 1
+  fi
+  
   case "$zram_type" in
-    swap) 
-      _mkswap "/dev/${_zram%%:*}" \
+    swap)
+      service_set_value zram "${_zram}:${zram_type}"
+      _mkswap "$_zram" \
         || ! _rmlock
       ;;
     ext4)
-      _mkstorage "/dev/${_zram%%:*}" \
+      service_set_value zram "${_zram}:${zram_type}"
+      _mkstorage "$_zram" \
         || ! _rmlock
       ;;
     *) 
@@ -314,11 +331,11 @@ stop() {
   _zram="$(service_get_value zram)"
   case ${_zram##*:} in
     swap)
-      _rmswap "/dev/${_zram%%:*}" \
+      _rmswap "${_zram%%:*}" \
         && _rmlock
       ;;
     ext4)
-      _rmstorage "/dev/${_zram%%:*}" \
+      _rmstorage "${_zram%%:*}" \
         && _rmlock
       ;;
   esac
